/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS 0x40023800UL

#define RCC_CR (RCC_BASE_ADDRESS + 0x00)

#define RCC_CFGR (RCC_BASE_ADDRESS + 0x08)

#define RCC_AHB1ENR (RCC_BASE_ADDRESS + 0x30)

#define GPIOA_BASE_ADDRESS 0x40020000UL

#define GPIOA_MODER (GPIOA_BASE_ADDRESS + 0x00)

#define GPIOA_AFRL_ADDRESS (GPIOA_BASE_ADDRESS + 0x20)

int main(void)
{
    /* Loop forever */
	//0. Enabling the HSE Clock
	uint32_t* pRCC_CR = (uint32_t*) RCC_CR;
	*pRCC_CR |= (1<<16);

	//1. Setting the MCO1 Clock as HSI
	uint32_t* pRCC_CFGR_REG = (uint32_t*) RCC_CFGR;
	*pRCC_CFGR_REG &= ~(3<<21);
	*pRCC_CFGR_REG |= (2<<21);
	*pRCC_CFGR_REG |= (6<<24);
	//*pRCC_CFGR_REG |= (3<<21);

	//2. Enabling the GPIOA RCC
	uint32_t* pRCC_AHB1ENR_REG = (uint32_t*) RCC_AHB1ENR;
	*pRCC_AHB1ENR_REG |= (1<<0);

	//3. Setting PA8 to alternate functionality AF0
	uint32_t* pGPIOA_MODER_REG = (uint32_t*) GPIOA_MODER;
	*pGPIOA_MODER_REG |= (2<<16);

	//4. Setting the alternate function of GPIO PA8
	uint32_t* pGPIOA_AFRL = (uint32_t*) GPIOA_AFRL_ADDRESS;
	*pGPIOA_AFRL |= 0;

//	for(;;);

}
