/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "LCD.h"

volatile LCD_Def_t LCD_Def;


int main(void) {
	delayUS(2 * 10000); // After power on wait for 1.5 ms minimum
	LCD_Init(&LCD_Def);

	LCD_Command_Send(&LCD_Def,0x80);

	char *data = "Neha Love";
	//char data[50];
	//display_lcd(data, strlen(data));
	LCD_Command_Send(&LCD_Def,0x0F);
	// Calculate shifts needed: Message Length (25) - Visible Characters (16) + 16
	// This shifts the message completely off the screen and then cycles back.
	//uint8_t scroll_steps = strlen(data);
	display_lcd(&LCD_Def,data, strlen(data)+1);
	while(1);
//	while (1) {
//		// Scroll the message one position to the LEFT at a time
//		for (uint8_t i = 0; i < scroll_steps; i++) {
//			// Command 0x18: Shift the entire display one position to the LEFT
//			LCD_Command_Send(SHIFT_LEFT);
//			// Wait for 200ms between shifts for speed control
//			delayUS(1 * 10000);
//		}
//
//		// Once the entire message has scrolled off the left side:
//
//		// Command 0x02: Return Home (resets cursor and display shift back to address 0x00)
//		LCD_Command_Send(0x02);
//		delayUS(2000); // Wait for Return Home to finish
//	}
//	uint32_t i = 0;
//	uint32_t decimal = 0;
//	uint32_t floating = 0;
//
//	while (1) {
//		i+=10;
//		decimal = i / 100;
//		floating = i % 100;
//		sprintf(data, "%d.%02d", (int)decimal, (int)floating);
//		display_lcd(LCD_Def,data, strlen(data)+1);
//		delayUS(1 * 200);
//	}
}

