/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx_gpio.h"

void delay(){
	for(int i = 0 ;i<100000;i++);
}
uint8_t check_input(){
	return gpio_read_pin(GPIOC, PIN_11);
}

int main(void)
{
	/** 1. Initialize the GPIO Pin PA0 */

       GPIOx_Handle_t GPIO_PA02_Handle = {0};
	GPIO_PA02_Handle.pGPIOx = GPIOA;
	GPIO_PA02_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_2;
	GPIO_PA02_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_OUTPUT;
	GPIO_PA02_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PA02_Handle.GPIO_CONFIG.GPIO_OP_TYPE = GPIO_OP_TYPE_PP;
	GPIO_PA02_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
	gpio_pin_init(&GPIO_PA02_Handle);

	GPIOx_Handle_t GPIO_PD12_Handle = {0};
	GPIO_PD12_Handle.pGPIOx = GPIOD;
	GPIO_PD12_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_12;
	GPIO_PD12_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_OUTPUT;
	GPIO_PD12_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PD12_Handle.GPIO_CONFIG.GPIO_OP_TYPE = GPIO_OP_TYPE_PP;
	GPIO_PD12_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
	gpio_pin_init(&GPIO_PD12_Handle);

	GPIOx_Handle_t GPIO_PD13_Handle = {0};
	GPIO_PD13_Handle.pGPIOx = GPIOD;
	GPIO_PD13_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_13;
	GPIO_PD13_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_OUTPUT;
	GPIO_PD13_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PD13_Handle.GPIO_CONFIG.GPIO_OP_TYPE = GPIO_OP_TYPE_PP;
	GPIO_PD13_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
	gpio_pin_init(&GPIO_PD13_Handle);

	GPIOx_Handle_t GPIO_PD14_Handle = {0};
	GPIO_PD14_Handle.pGPIOx = GPIOD;
	GPIO_PD14_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_14;
	GPIO_PD14_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_OUTPUT;
	GPIO_PD14_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PD14_Handle.GPIO_CONFIG.GPIO_OP_TYPE = GPIO_OP_TYPE_PP;
	GPIO_PD14_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
	gpio_pin_init(&GPIO_PD14_Handle);

	GPIOx_Handle_t GPIO_PD15_Handle = {0};
	GPIO_PD15_Handle.pGPIOx = GPIOD;
	GPIO_PD15_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_15;
	GPIO_PD15_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_OUTPUT;
	GPIO_PD15_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PD15_Handle.GPIO_CONFIG.GPIO_OP_TYPE = GPIO_OP_TYPE_PP;
	GPIO_PD15_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
	gpio_pin_init(&GPIO_PD15_Handle);

	/** 2. Initialize the User Button */
//	GPIOx_Handle_t GPIO_PA0_Handle = {0};
//	GPIO_PA0_Handle.pGPIOx = GPIOA;
//	GPIO_PA0_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_0;
//	GPIO_PA0_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_INPUT;
//	GPIO_PA0_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
//	GPIO_PA0_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_NONE;
//	gpio_pin_init(&GPIO_PA0_Handle);
	GPIOx_Handle_t GPIO_PC11_Handle = {0};
	GPIO_PC11_Handle.pGPIOx = GPIOC;
	GPIO_PC11_Handle.GPIO_CONFIG.GPIO_PIN_NUMBER = PIN_11;
	GPIO_PC11_Handle.GPIO_CONFIG.GPIO_MODE = GPIO_MODE_INPUT;
	GPIO_PC11_Handle.GPIO_CONFIG.GPIO_SPEED = GPIO_SPEED_MEDIUM;
	GPIO_PC11_Handle.GPIO_CONFIG.GPIO_PU_PD = GPIO_PU_PD_PULL_DOWN;
	gpio_pin_init(&GPIO_PC11_Handle);
	/** 3. Toggle the LED */
	while(1){
		while(!check_input());
		gpio_toggle_pin(GPIOD, PIN_12);
		delay();
		while(!check_input());
		gpio_toggle_pin(GPIOD, PIN_12);
		while(!check_input());

		gpio_toggle_pin(GPIOD, PIN_13);
		while(!check_input());
		delay();
		while(!check_input());
		gpio_toggle_pin(GPIOD, PIN_13);
		while(!check_input());

		gpio_toggle_pin(GPIOD, PIN_14);
		while(!check_input());
		delay();
		while(!check_input());
		gpio_toggle_pin(GPIOD, PIN_14);
		while(!check_input());

		gpio_toggle_pin(GPIOD, PIN_15);
		while(!check_input());
		delay();
		while(!check_input());
		gpio_toggle_pin(GPIOD, PIN_15);


		while(!check_input());
		gpio_toggle_pin(GPIOA, PIN_2);
		delay();
		while(!check_input());
		gpio_toggle_pin(GPIOA, PIN_2);
	}

}
